apiVersion: v1
kind: Service
metadata:
  labels:
    app: dockerized-react-app
  name: dockerized-react-app-svc
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: dockerized-react-app
  type: ClusterIP
status:
  loadBalancer: {}
